"""empty message

Revision ID: d9fa01a6b167
Revises: a76043764481
Create Date: 2019-05-23 17:19:54.662739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9fa01a6b167'
down_revision = 'a76043764481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('googleAccessToken', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('googleId', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'password')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'name')
    op.drop_column('user', 'googleId')
    op.drop_column('user', 'googleAccessToken')
    # ### end Alembic commands ###
