"""users table

Revision ID: fcc3bc594699
Revises: b53adbf5d654
Create Date: 2019-05-20 16:25:12.156869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcc3bc594699'
down_revision = 'b53adbf5d654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'role')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
